#
# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable SPI and use of external flash.
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

# Enable multithreading.
CONFIG_MULTITHREADING=y

# MCUboot requires a large stack size, otherwise an MPU fault will occur.
CONFIG_MAIN_STACK_SIZE=16384

# Enable flash operations
CONFIG_FLASH=y

# Increase default MCUBoot partition size because of the added SPI drivers multi threading.
CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x10000

# This config is needed because SPI NOR is not a device specific DT node.
# This can be removed when DT_CHOSEN(nor,pm-ext-flash) is set by a Kconfig.
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

# Disable Serial since it uses the same serial as logging.
CONFIG_MCUBOOT_SERIAL=n
CONFIG_BOOT_MAX_IMG_SECTORS=256

# Make sure SPI read/writes are word aligned using RAM buffer.
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=32

# First step of any MCUboot debugging is to enable log.
CONFIG_LOG=y
